In [1]:
# 1차원 배열 인덱싱
import numpy as np

arr = np.arange(16)
print(f"arr = {np.array2string(arr, separator=', ')}")

# 기본 인덱싱
# 0부터 값 시작.
# [start : end - 1]까지 출력.
# 음수 값으로 인덱싱 가능.
basic_idx = arr[5]
print(f"\narr의 index 값이 5인 원소: {arr[5]}")

# 음수 인덱스
minus_idx = arr[-1]
print(f"\narr의 index 값이 -1인 원소: {arr[-1]}")

# 슬라이싱
idx_slicing = arr[5:8]
print(f"\n지정된 범위를 슬라이싱 한 결과: {np.array2string(arr[5:8], separator=', ')}")

arr = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]

arr의 index 값이 5인 원소: 5

arr의 index 값이 -1인 원소: 15

지정된 범위를 슬라이싱 한 결과: [5, 6, 7]


In [2]:
# 인덱스를 사용한 값 할당

# 단일 값 할당
arr[5] = 100
print(f"단일 값을 할당한 결과: {np.array2string(arr, separator=', ')}")

# 여러 값 할당
arr[6:8] = [101, 102]
print(f"\n다중 값을 할당한 결과: {np.array2string(arr, separator=', ')}")

단일 값을 할당한 결과: [  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,  13,  14,
  15]

다중 값을 할당한 결과: [  0,   1,   2,   3,   4, 100, 101, 102,   8,   9,  10,  11,  12,  13,  14,
  15]


In [3]:
# 다차원 배열의 인덱싱
# 한 행 전체 선택, 개별 요소 선택 등의 방법 사용 가능.
# 2차원 배열로 진행.
arr02 = np.arange(16).reshape(4, 4)                 # 길이가 4인 1차원 배열이 4개인 2차원 배열 생성. 값은 1부터 16까지 총 16개.
print(f"{np.array2string(arr02, separator=', ')}")

print(f"\n한 행을 전체 선택해보기: {np.array2string(arr02[1], separator=', ')}")        # arr02의 두 번째 행(index 값으로 1이기 때문) 전체를 출력해보기.

print(f"\n개별 요소를 선택하는 방법 01: {np.array2string(arr02[1][1], separator=', ')}")    # index 값이 1인 1차원 배열의 index 값이 1인 요소를 출력.
print(f"\n개별 요소를 선택하는 방법 02: {np.array2string(arr02[1, 2], separator=', ')}")    # index 값이 1인 1차원 배열의 index 값이 2인 요소를 출력.

arr02[1, 1] = 100       # 2차원 배열의 index 값이 1인 1차원 배열의 index 값이 1인 요소에 값을 100으로 변경.
print(f"\n1차 단일값 할당 결과: \n{np.array2string(arr02, separator=', ')}")

arr02[1, 2] = 101       # 2차원 배열의 index 값이 1인 1차원 배열의 index 값이 2인 요소에 값을 101로 변경.
print(f"\n2차 단일값 할당 결과: \n{np.array2string(arr02, separator=', ')}")


# 2차원 배열의 슬라이싱
# 행 슬라이싱
# ':' 기준으로 좌측값 생략 시 0부터 시작, 우측값 생략 시 배열의 크기만큼 적용.
print(f"\n2차원 배열의 행 슬라이싱 01: \n{np.array2string(arr02[0:2], separator=', ')}")        # list slicing과 방법 동일.
print(f"\n2차원 배열의 행 슬라이싱 02: \n{np.array2string(arr02[:2], separator=', ')}")         # list slicing과 방법 동일.

# 2차원 슬라이싱
# 행과 열을 동시에 지정하는 슬라이싱
print(f"\n행과 열을 동시에 지정하는 2차원 슬라이싱 01 ==> \n{np.array2string(arr02[0:2, 2:4], separator=', ')}")
print(f"\n행과 열을 동시에 지정하는 2차원 슬라이싱 02 ==> \n{np.array2string(arr02[:2, 2:], separator=', ')}")

[[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15]]

한 행을 전체 선택해보기: [4, 5, 6, 7]

개별 요소를 선택하는 방법 01: 5

개별 요소를 선택하는 방법 02: 6

1차 단일값 할당 결과: 
[[  0,   1,   2,   3],
 [  4, 100,   6,   7],
 [  8,   9,  10,  11],
 [ 12,  13,  14,  15]]

2차 단일값 할당 결과: 
[[  0,   1,   2,   3],
 [  4, 100, 101,   7],
 [  8,   9,  10,  11],
 [ 12,  13,  14,  15]]

2차원 배열의 행 슬라이싱 01: 
[[  0,   1,   2,   3],
 [  4, 100, 101,   7]]

2차원 배열의 행 슬라이싱 02: 
[[  0,   1,   2,   3],
 [  4, 100, 101,   7]]

행과 열을 동시에 지정하는 2차원 슬라이싱 01 ==> 
[[  2,   3],
 [101,   7]]

행과 열을 동시에 지정하는 2차원 슬라이싱 02 ==> 
[[  2,   3],
 [101,   7]]


In [4]:
# Boolean Indexing
# 불리언 인덱싱
# 배열에서 원하는 값이 있는 위치에는 True, 아닌 곳에는 False를 넣은 불리언 배열을 만들어 인덱싱을 사용.

# 불리언 인덱싱의 개념
# 특정 조건을 만족하는 값을 필터링 할 때 많이 사용.
# ex) 성적이 들어있는 배열에서 90점 이상의 점수만 선택하려고 할 때
# 성적이 들어있는 배열과 동일한 크기의 불리언 배열 생성
# 조건을 만족하는 인덱스 위치에는 True, 만족하지 않는 위치에는 False를 삽입.
# 불리언 배열을 인덱스로 사용하면 True가 들어있는 위치의 값만 반환됨.
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
print(f"성적 배열 ==> {np.array2string(score_arr, separator=', ')}")
print(f"\n90점 이상인지 여부를 확인하는 불리언 배열 ==> {np.array2string(score_arr >= 90, separator=', ')}")
print(f"\n90점 이상인 점수만 추출해 배열을 생성 ==> {np.array2string(score_arr[score_arr >= 90], separator=', ')}")

# 불리언 인덱싱으로 조건을 충족하는 위치의 값을 변경하기. (잘못된 코드)
def wrong_code():
    """print(f"\n불리언 인덱싱을 활용해 조건을 충족하는 위치의 값을 변경하기 ==> {np.array2string(score_arr[score_arr >= 90]= 999, separator=', ')}")      # f-string의 {}(=표현식)에는 대입 사용 불가능.
    # f-string의 {} 안에 들어갈 수 있는 것들
    # 01. 대입없는 단순한 값 계산.
    # 02. 함수 호출
    # 03. 인덱싱
    # 04. 비교
    'score_arr[score_arr >= 90] = 999'는 실제로 조건에 맞는 값을 999로 변환해야 하기 때문에, f-string에서 반환이 불가능함.
    해결 방법은 값을 먼저 따로 변경하고, 그 다음에 출력해야 함.
    그리고 함수를 정의하고 호출을 하지 않더라도, 함수 내용에는 문법 오류가 없어야 함.
    왜냐하면 Python은 소스 전체를 먼저 pharsing 하고 문법 오류가 존재하면 실행 전 즉시 중단함.
    그래서 함수 호출 여부를 판단하기 이전에 문법 오류가 존재하기 때문에, 호출을 하지 않더라도 에러가 발생함.
    Python은 문법 오류를 절대 용납하지 않고, 그래서 문법 오류가 있으면 실행이 즉시 중단됨. 이는 대규모 코드베이스의 안정성을 위한 설계 의도.
    그래서 주석 처리를 하기 싫었는데 어쩔 수 없이 문자열로 길게 적음."""
    pass

# 불리언 인덱싱으로 조건을 충족하는 위치의 값을 변경하기. (정상 코드)
score_arr02 = score_arr.copy()
score_arr02[score_arr02 >= 90] = 999
print(f"\n90점 이상인 원소를 999로 변환한 배열 ==> {np.array2string(score_arr02, separator=', ')}")

성적 배열 ==> [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]

90점 이상인지 여부를 확인하는 불리언 배열 ==> [False,  True, False, False, False,  True,  True, False, False, False]

90점 이상인 점수만 추출해 배열을 생성 ==> [90, 95, 90]

90점 이상인 원소를 999로 변환한 배열 ==> [ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80]


In [5]:
# 팬시 인덱싱(fancy indexing)
# 정수 배열을 사용하여 원하는 위치의 요소들을 선택하는 방법.
fancy_arr = np.arange(20)
indices = [1, 3, 5, 7]      # 특정 인덱스만 선택하는 정수 배열.
print(f"1차원 배열에서의 fancy indexing 사용 결과 ==> {np.array2string(fancy_arr[indices], separator=', ')}")

fancy_arr02 = np.arange(12).reshape(3, 4)       # 길이가 4인 1차원 배열 3개로 구성된 2차원 배열 생성.
print(f"\n{fancy_arr02}")
print(f"\n2차원 배열에서의 fancy indexing 사용 결과 ==> {np.array2string(fancy_arr02[[0, 2], [1, 3]], separator=', ')}")        # index 값이 0인 1차원 배열에서 2번째 원소, index 값이 1인 

1차원 배열에서의 fancy indexing 사용 결과 ==> [1, 3, 5, 7]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

2차원 배열에서의 fancy indexing 사용 결과 ==> [ 1, 11]


In [6]:
# 'Broadcasting'을 잘 이해하기 위한 예제 코드
# Broadcasting 예제 01
# 스칼라는 모든 원소에 적용됨.
# shape를 맞추기 위해 필요한 만큼 반복된 것처럼 동작함.
a = np.array([1, 2, 3]) # (1, 3)
b = 2                   # 스칼라(0차원)
print("a:", a, "shape:", a.shape)
print("b:", b, "type:", type(b))
print("\n")

# Broadcasting 예제 02
# (3, 1) + (1, 4) = (3, 4)
ex01 = np.arange(3).reshape(3, 1)       # (3, 1)
ex02 = np.arange(10, 14).reshape(1, 4)  # (1, 4)

print("ex01=\n", ex01, "\nshape:", ex01.shape)
print("ex02=\n", ex02, "\nshape:", ex02.shape)

ex03 = ex01 + ex02
print("ex01 + ex02 =\n", ex03, "\nshape:", ex03.shape)

# Broadcasting 예제 03
# (4, )는 (1, 4처럼 취급될 때가 더 많음. (차원 맞추기 규칙)
print("\n")
ex04 = np.arange(12).reshape(3, 4)      # (3, 4)
ex05 = np.array([100, 200, 300, 400])   # (4, )

print("ex04 shape:", ex04.shape)
print("ex05 shape:", ex05.shape)

ex06 = ex04 + ex05
print("ex04 + ex05=\n", ex06)
print("result shape:", ex06.shape)      # (4, )가 (1, 4)로 됨. 1차원 배열을 2차원으로 맞춰서 (1, 4)로 취급한 것.

# Broadcasting 예제 04
# Broadcasting이 불가능한 경우
print("\n")
ex07 = np.ones((3, 2))          # 모든 원소가 1인 2차원 배열 (3, 2)
ex08 = np.ones((3, 3))          # 모든 원소가 1인 2차원 배열 (3, 3)

print("ex07 shape:", ex07.shape)
print("ex08 shape:", ex08.shape)

try:
    print(ex07 + ex08)
except ValueError as e:
    print("ValueError 발생:", e)

# Broadcasting 예제 05
# 'np.broadcast_shapes'를 사용하여 broadcasting 가능 또는 불가능 여부 파악하기.
pairs = [
    ((3, 1), (1, 4)),
    ((3, 4), (4, )),
    ((3, 2), (3, 3)),
    ((3, 4), (4, 3)),
    ((2, 3), (4, 3)),
    ((3, 3), (1, 1))
]

for s1, s2 in pairs:
    print("\nshapes:", s1, "and", s2)
    try:
        out = np.broadcast_shapes(s1, s2)
        print("broadcast shape:", out)
    except ValueError as e:
        print("braodcast 불가:", e)

a: [1 2 3] shape: (3,)
b: 2 type: <class 'int'>


ex01=
 [[0]
 [1]
 [2]] 
shape: (3, 1)
ex02=
 [[10 11 12 13]] 
shape: (1, 4)
ex01 + ex02 =
 [[10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]] 
shape: (3, 4)


ex04 shape: (3, 4)
ex05 shape: (4,)
ex04 + ex05=
 [[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]
result shape: (3, 4)


ex07 shape: (3, 2)
ex08 shape: (3, 3)
ValueError 발생: operands could not be broadcast together with shapes (3,2) (3,3) 

shapes: (3, 1) and (1, 4)
broadcast shape: (3, 4)

shapes: (3, 4) and (4,)
broadcast shape: (3, 4)

shapes: (3, 2) and (3, 3)
braodcast 불가: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3, 2) and arg 1 with shape (3, 3).

shapes: (3, 4) and (4, 3)
braodcast 불가: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3, 4) and arg 1 with shape (4, 3).

shapes: (2, 3) and (4, 3)
braodcast 불가: shape mismatch: objects cannot be broadcast to a 

In [7]:
# 2차원 shape 더 잘 이해할 수 있는 GPT의 예제
# 예제 01. 같은 값이라도 shape가 다르면, 출력 및 연산이 달라짐.
ex0201 = np.array([1, 2])       # (2, ) ==> 1차원
ex0202 = np.array([[1], [2]])   # (2, 1) ==> 2차원
ex0203 = np.array([[1, 2]])     # (1, 2) ==> 2차원

print("ex0201:", ex0201, "shape:", ex0201.shape)
print("ex0202:", ex0202, "shape:", ex0202.shape)
print("ex0203:", ex0203, "shape:", ex0203.shape)

# 예제 02. 전치(transpose): (2, 1) <-> (1, 2)
# '.T'를 사용하면 2차원 이상 배열에서 축 뒤집기 가능. (열과 행을 서로 바꾸기)
ex0204 = np.array([[1], [2]])       # (2, 1)
print("\nex0204 shape:", ex0204.shape)
print("ex0204 transpose shape:", ex0204.T.shape)
print("ex0204=", ex0204)
print("ex0204.T=", ex0204.T)

# 예제 03. 격자가 생기는 이유. (2, 1) + (1, 2) = (2, 2)
# 지금 이 형태는 broadcasting이 진행됨. (교차 조합)
ex0205 = np.array([[10], [20]])             # (2, 1)
ex0206 = np.array([[1, 2]])                 # (1, 2)

print("\nex0205 shape:", ex0205.shape)
print("ex0206 shape:", ex0206.shape)

ex0207 = ex0205 + ex0206
print("ex0205 + ex0206 =", ex0207)
print("ex0207 shape:", ex0207.shape)

# 예제 04. 축(axis)별 합계: (2, 1)과 (1, 2)의 axis 의미가 서로 다름.
# 'axis = 0': 행 방향으로 내려감.
# 'axis = 1': 열 방향으로 가로로 이동.
ex0208 = np.array([[1], [2]])       # (2, 1)
ex0209 = np.array([[1, 2]])         # (1, 2)

print("\nex0208 sum axis=0:", ex0208.sum(axis=0), "shape:", ex0208.sum(axis=0).shape)
print("ex0208 sum axis=1:", ex0208.sum(axis=1), "shape:", ex0208.sum(axis=1).shape)

print("ex0209 sum axis=0:", ex0209.sum(axis=0), "shape:", ex0209.sum(axis=0).shape)
print("ex0209 sum axis=1:", ex0209.sum(axis=1), "shape:", ex0209.sum(axis=1).shape)

# 예제 05. 인덱싱 결과 shape 확인하기
# 행을 하나만 선택하면 (1, n)이 아니라 (n, )이 되는 경우가 많음.
# 슬라이싱은 차원을 그대로 유지하는 경향이 있어, 'broadcasting/행렬연산'에 유리할 때가 많음. 
ex0210 = np.arange(12).reshape(3, 4)

row0 = ex0210[0]        # 보통 (4, )로 1차원 형태가 됨.
row0_2d = ex0210[0:1]   # (1, 4)로 2차원 유지. (슬라이스)

print("\nex0210:", ex0210)
print("ex0210 shape:", ex0210.shape)
print("row0 shape:", row0.shape, "=>", row0)
print("row0_2d shape:", row0_2d.shape, "=>", row0_2d)

ex0201: [1 2] shape: (2,)
ex0202: [[1]
 [2]] shape: (2, 1)
ex0203: [[1 2]] shape: (1, 2)

ex0204 shape: (2, 1)
ex0204 transpose shape: (1, 2)
ex0204= [[1]
 [2]]
ex0204.T= [[1 2]]

ex0205 shape: (2, 1)
ex0206 shape: (1, 2)
ex0205 + ex0206 = [[11 12]
 [21 22]]
ex0207 shape: (2, 2)

ex0208 sum axis=0: [3] shape: (1,)
ex0208 sum axis=1: [1 2] shape: (2,)
ex0209 sum axis=0: [1 2] shape: (2,)
ex0209 sum axis=1: [3] shape: (1,)

ex0210: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ex0210 shape: (3, 4)
row0 shape: (4,) => [0 1 2 3]
row0_2d shape: (1, 4) => [[0 1 2 3]]


In [8]:
# 'np.ix_' 예제
# 'np.ix_': 여러 1차원 인덱스 목록을 받아서 'open mesh' 인덱스 배열을 만들고, 그걸로 행과 열의 교차조합을 쉽게 뽑게 해줌.

# 예제 01. pair indexing vs np.ix_ cross indexing
ex0301 = np.arange(12).reshape(3, 4)
rows = [0, 2]
cols = [1, 3]

print("ex0301=", ex0301)
pair = ex0301[rows, cols]
print("\n[rows, cols] (pairwise) =>", pair, "shape:", pair.shape)

cross = ex0301[np.ix_(rows, cols)]
print("\nex0301[np.ix_(rows, cols)] (cross product) =>", cross, "shape:", cross.shape)

# 예제 02. shape 명령어를 사용해 'np.ix_'가 실제로 어떤 인덱스 배열을 만드는지 확인.
# 'np.ix_'에서는 보통 'r = (2, 1), c = (1, 2)'가 됨.
# 이 shape가 바로 broadcasting을 유도해 '2x2 격자 인덱싱'을 가능하게 함.
rows01 = [0, 2]
cols01 = [1, 3]

r, c = np.ix_(rows01, cols01)
print("\nr=", r, "shape:", r.shape)
print("c=", c, "shape:", c.shape)

# 예제 03. 'np.ix_'로 부분행렬(submatrix) 뽑기.
# 실무에서 제일 자주 사용하는 기법.
# 특정 행들과 특정 열들의 조합을 한 번에 추출하는 대표 패턴.
ex0302 = np.arange(1, 26).reshape(5, 5)
rows02 = [1, 3, 4]
cols02 = [0, 2]
sub = ex0302[np.ix_(rows02, cols02)]

print("\nex0302=", ex0302)
print("rows:", rows02, "cols:", cols02)
print("submatrix=", sub, "shape:", sub.shape)

# 예제 04. Boolean(= mask)도 'np.ix_' 입력 가능.
# 'np.ix_'는 정수 인덱스 뿐만 아니라 Boolean Sequence도 받아서 해당 축의 mask처럼 동작할 수 있음.
ex0303 = np.arange(1, 17).reshape(4, 4)

row_mask = np.array([True, False, True, False])     # 행은 (0, 2)
col_mask = np.array([False, True, True, False])     # 열은 (1, 2)
sub = ex0303[np.ix_(row_mask, col_mask)]

print("\nex0303=", ex0303)
print("row_mask:", row_mask)
print("col_mask:", col_mask)
print("ex0303[np.ix_(row_mask, col_mask)]=", sub, "shape:", sub.shape)

# 예제 05. 'np.ix_'로 '블록 대입(assign)' 하기.
# pairwise와 결과가 완전히 다름.
# 데이터 전처리에서 '특정 행/열 조합을 한꺼번에 수정할 때' np.ix_를 사용해야 안전하고 의도가 명확함.
ex0304 = np.arange(12).reshape(3, 4)
ex0305 = ex0304.copy()

rows03 = [0, 2]
cols03 = [1, 3]

ex0304[rows03, cols03] = -1             # pairwise를 대입해 (0, 1), (2, 3) 두 점만 바뀌게 동작.
ex0305[np.ix_(rows03, cols03)] = -1     # np.ix_를 사용한 cross-product 대입을 사용해 '2x2' 블록이 바뀌게 동작.

print("\n원본 기반 pairwise 대입 결과=", ex0304)
print("원본 기반 cross-product 대입 결과=", ex0305)

ex0301= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[rows, cols] (pairwise) => [ 1 11] shape: (2,)

ex0301[np.ix_(rows, cols)] (cross product) => [[ 1  3]
 [ 9 11]] shape: (2, 2)

r= [[0]
 [2]] shape: (2, 1)
c= [[1 3]] shape: (1, 2)

ex0302= [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
rows: [1, 3, 4] cols: [0, 2]
submatrix= [[ 6  8]
 [16 18]
 [21 23]] shape: (3, 2)

ex0303= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row_mask: [ True False  True False]
col_mask: [False  True  True False]
ex0303[np.ix_(row_mask, col_mask)]= [[ 2  3]
 [10 11]] shape: (2, 2)

원본 기반 pairwise 대입 결과= [[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 -1]]
원본 기반 cross-product 대입 결과= [[ 0 -1  2 -1]
 [ 4  5  6  7]
 [ 8 -1 10 -1]]


In [19]:
# np.ix_가 도저히 이해가 잘 안되서, GPT한테 예제 10개를 만들어달라고 요청함.
# 출력을 보기 좋게 하기 위한 코드
def banner(title):
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)

# 예제 01. 'np.ix_'는 열벡터/행벡터 모양의 인덱스 2개를 만듦.
banner("예제 01) np.ix_가 반환하는 r, c의 shape를 확인.")

rows = [0, 2]
cols = [1, 3]

r, c = np.ix_(rows, cols)

print("rows:", rows)
print("cols:", cols)
print("r=\n", r, "shape:", r.shape)
print("c=\n", c, "shape:", c.shape)

assert r.shape == (2, 1)
assert c.shape == (1, 2)


예제 01) np.ix_가 반환하는 r, c의 shape를 확인.
rows: [0, 2]
cols: [1, 3]
r=
 [[0]
 [2]] shape: (2, 1)
c=
 [[1 3]] shape: (1, 2)


In [16]:
# 예제 02. 'pairwise' vs 'cross product'
banner("예제 02) pairwise vs cross product의 차이")

ex02 = np.arange(12).reshape(3, 4)
rows = [0, 2]
cols = [1, 3]

pair = ex02[rows, cols]
cross = ex02[np.ix_(rows, cols)]

print("ex02=\n", ex02)
print("ex02[rows, cols] (pairwise) =", pair, "shape:", pair.shape)
print("ex02[np.ix_(rows, cols)] (cross product)=\n", cross, "shape:", cross.shape)

expected_pair = np.array([ex02[0, 1], ex02[2, 3]])        # pairwise는 (0, 1), (2, 3) 두 점만 조합함.
assert np.array_equal(pair, expected_pair)

expected_cross = np.array([[ex02[0, 1], ex02[0, 3]], [ex02[2, 1], ex02[2, 3]]])     # cross는 (0, 1), (0, 3), (2, 1), (2, 3)으로 총 2x2 조합을 생성.
assert np.array_equal(cross, expected_cross)


예제 02) pairwise vs cross product의 차이
ex02=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ex02[rows, cols] (pairwise) = [ 1 11] shape: (2,)
ex02[np.ix_(rows, cols)] (cross product)=
 [[ 1  3]
 [ 9 11]] shape: (2, 2)


In [17]:
# 예제 03. np.ix_는 교차 조합 인덱싱을 보장함. (= 부분행렬 추출)
banner("예제 03) 부분행렬(submatrix) 추출")

x = np.arange(1, 26).reshape(5, 5)
rows = [1, 3, 4]
cols = [0, 2]
sub = x[np.ix_(rows, cols)]

print("x=\n", x)
print("rows:", rows, "cols:", cols)
print("sub=\n", sub, "shape:", sub.shape)

assert sub.shape == (len(rows), len(cols))
assert sub[0, 0] == x[1, 0]         # 랜덤으로 몇 개의 값이 맞는지 체크하는 검증.
assert sub[0, 1] == x[1, 2]
assert sub[2, 1] == x[4, 2]


예제 03) 부분행렬(submatrix) 추출
x=
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
rows: [1, 3, 4] cols: [0, 2]
sub=
 [[ 6  8]
 [16 18]
 [21 23]] shape: (3, 2)


In [18]:
# 예제 04. np.ix_가 '브로드캐스팅 격자'를 만드는 것을 직접 보기.
banner("예제 04) ix_ 인덱스가 브로드캐스팅으로 격자화되는 과정")

x = np.arange(12).reshape(3, 4)
rows = [0, 2]
cols = [1, 3]
r, c = np.ix_(rows, cols)

R = np.broadcast_to(r, (len(rows), len(cols)))      # 개념 확인을 위한 브로드캐스팅 된 인덱스 격자 01
C = np.broadcast_to(c, (len(rows), len(cols)))      # 개념 확인을 위한 브로드캐스팅 된 인덱스 격자 02

print("r shape:", r.shape, "\n", r)
print("c shape:", c.shape, "\n", c)
print("broadcast R=\n", R, "shape:", R.shape)
print("broadcast C=\n", C, "shape:", C.shape)

manual = np.empty((len(rows), len(cols)), dtype=x.dtype)        # 격자 위치 [i, j] 마다 x[R[i, j], C[i, j]]를 뽑는 것과 동일.
for i in range(len(rows)):
    for j in range(len(cols)):
        manual[i, j] = x[R[i, j], C[i, j]]

auto = x[np.ix_(rows, cols)]
print("manual=\n", manual)
print("auto=\n", auto)

assert np.array_equal(manual, auto)


예제 04) ix_ 인덱스가 브로드캐스팅으로 격자화되는 과정
r shape: (2, 1) 
 [[0]
 [2]]
c shape: (1, 2) 
 [[1 3]]
broadcast R=
 [[0 0]
 [2 2]] shape: (2, 2)
broadcast C=
 [[1 3]
 [1 3]] shape: (2, 2)
manual=
 [[ 1  3]
 [ 9 11]]
auto=
 [[ 1  3]
 [ 9 11]]


In [20]:
# 예제 05. 'np.ix_'는 Boolean mask도 받음.
# 즉, 행/열 마스크로 부분행렬 생성 가능.
# 공식 문서에서 'Boolean sequence'는 mask로 해석된다고 설명함.
banner("예제 05) boolean mask와 np.ix_")

X = np.arange(1, 17).reshape(4, 4)
row_mask = np.array([True, False, True, False])     # 0행, 2행
col_mask = np.array([False, True, True, False])     # 1열, 2열

sub = X[np.ix_(row_mask, col_mask)]

print("X=\n", X)
print("row_mask:", row_mask)
print("col_mask:", col_mask)
print("sub=\n", sub, "shape:", sub.shape)

assert sub.shape == (row_mask.sum(), col_mask.sum())        # 기대 shape = (선택된 행 개수, 선택된 열 개수)
assert np.array_equal(sub, X[[0, 2]][:, [1, 2]])


예제 05) boolean mask와 np.ix_
X=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row_mask: [ True False  True False]
col_mask: [False  True  True False]
sub=
 [[ 2  3]
 [10 11]] shape: (2, 2)


In [ ]:
# 예제 06. 대입(assignment)에서의 'np.ix_'의 중요성
# np.ix_ 대입은 블록 전체가 바뀜. (pairwise는 몇개의 점만 바뀜.)
banner("예제 06) pairwise 대입 vs np.ix_ 대입")

X = np.arange(12).reshape(3, 4)
rows = [0, 2]
cols = [1, 3]

a = X.copy()
b = X.copy()

a[rows, cols] = -1              # 점 2개만 -1로 변경.
b[np.ix_(rows, cols)] = -1      # 2x2 전체를 -1로 변경.

print("원본 X=\n", X)
print("a (pairwise assign)=\n", a)
print("b (ix_ assign)=\n", b)

assert a[0, 1] == -1 and a[2, 3] == -1          # a는 pairwise라 (0, 1), (2, 3)의 값만 -1임.
assert a[0, 3] == -1 and a[2, 1] != -1          # 이것은 조건 성립이 안됨. AssertionError 발생.
assert np.all(b[np.ix_(rows, cols)] == -1)      # b는 np.ix_를 사용해서 2x2 블록의 값이 모두 -1.


예제 06) pairwise 대입 vs np.ix_ 대입
원본 X=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a (pairwise assign)=
 [[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 -1]]
b (ix_ assign)=
 [[ 0 -1  2 -1]
 [ 4  5  6  7]
 [ 8 -1 10 -1]]


AssertionError: 

In [22]:
# 예제 07. 3차원 배열에서 앞의 두 축을 교차로 선택.
# 'np.ix_'는 N개의 1차원 sequence를 받아 N개의 인덱스 배열을 반환함.
# 즉, 축 수만큼 인덱스를 제공함.
banner("예제 07) 3차원에서 앞 두 축을 cross로 선택하고, 마지막 축은 유지하기.")

A = np.arange(2*3*4).reshape(2, 3, 4)       # 이 문장은 (2, 3, 4)를 의미함.
i = [0, 1]          # 첫번째 축에서 (0, 1)을 선택.
j = [0, 2]          # 두번째 축에서 (0, 2)를 선택.

sub = A[np.ix_(i, j) + (slice(None),)]      # np.ix_는 i와 j에 대한 open mesh를 만들고, 마지막 축은 그대로 유지함.

print("A shape:", A.shape)
print("sub shape:", sub.shape)
print("sub=\n", sub)

assert sub.shape == (len(i), len(j), A.shape[2])        # 기대 shape: (len(i), len(j), 4)
assert np.array_equal(sub[0, 0, :], A[0, 0, :])
assert np.array_equal(sub[1, 1, :], A[1, 2, :])


예제 07) 3차원에서 앞 두 축을 cross로 선택하고, 마지막 축은 유지하기.
A shape: (2, 3, 4)
sub shape: (2, 2, 4)
sub=
 [[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [20 21 22 23]]]


In [23]:
# 예제 08. np.ix_는 입력이 반드시 1차원 sequence.
banner("예제 08) np.ix_의 입력은 1차원 sequence여야 함. (실수 예방)")

try:
    bad = np.ix_(np.array([[0, 1]]), [0, 2])        # 1차원이 아닌 값을 넣으면 의도와 다르게 동작하거나 에러 유발.
    print("bad:", bad)
except Exception as e:
    print("예상대로 문제가 발생:", repr(e))

good = np.ix_(np.array([0, 1]), np.array([0, 2]))
print("good shapes:", [g.shape for g in good])

assert good[0].shape == (2, 1)
assert good[1].shape == (1, 2)


예제 08) np.ix_의 입력은 1차원 sequence여야 함. (실수 예방)
예상대로 문제가 발생: ValueError('Cross index must be 1 dimensional')
good shapes: [(2, 1), (1, 2)]


In [25]:
# 예제 09. 'np.ix_'는 사실상 row를 column vector, col을 row vector로 reshape 한 것과 같음.
# 'np.ix_(rows, cols)'는 'rows.reshape(-1, 1)', 'cols.reshape(1, -1)' 형태를 만들어 준다고 이해하기.
banner("예제 09) 'np.ix_'는 (len(rows), 1)과 (1, len(cols))를 만들어 브로드캐스팅을 유도함.")

X = np.arange(12).reshape(3, 4)
rows = np.array([0, 2])
cols = np.array([1, 3])
ix_r, ix_c = np.ix_(rows, cols)

manual_r = rows.reshape(-1, 1)      # (2, 1)로 됨.
manual_c = cols.reshape(1, -1)      # (1, 2)로 됨.

print("ix_r shape:", ix_r.shape, "manual_r shape:", manual_r.shape)
print("ix_c shape:", ix_c.shape, "manual_c.shape:", manual_c.shape)

assert np.array_equal(ix_r, manual_r)
assert np.array_equal(ix_c, manual_c)

a = X[np.ix_(rows, cols)]       # 인덱싱 결과도 동일해야 함.
b = X[manual_r, manual_c]
print("a=\n", a)
print("b=\n", b)

assert np.array_equal(a, b)


예제 09) 'np.ix_'는 (len(rows), 1)과 (1, len(cols))를 만들어 브로드캐스팅을 유도함.
ix_r shape: (2, 1) manual_r shape: (2, 1)
ix_c shape: (1, 2) manual_c.shape: (1, 2)
a=
 [[ 1  3]
 [ 9 11]]
b=
 [[ 1  3]
 [ 9 11]]


In [ ]:
# 예제 10. 실무에서 쓰이는 'np.ix_'를 쓰는 이유
# 교차 조합 부분행렬을 만들기 위해 사용.
banner("예제 10) 부분행렬 추출: ix_ vs 단계 인덱싱 비교")

X = np.arange(1, 26).reshape(5, 5)
rows = [1, 3, 4]
cols = [0, 2]

sub_ix = X[np.ix_(rows, cols)]              # 교차 조합 부분행렬이라는 의미가 코드에 바로 드러남.
sub_step = X[rows][:, cols]

print("sub_ix=\n", sub_ix)
print("sub_step=\n", sub_step)

assert np.array_equal(sub_ix, sub_step)


예제 10) 부분행렬 추출: ix_ vs 단계 인덱싱 비교
sub_ix=
 [[ 6  8]
 [16 18]
 [21 23]]
sub_step=
 [[ 6  8]
 [16 18]
 [21 23]]


In [ ]:
# 다중 조건 불리언 인덱싱
# 다중 조건 사용 시 논리 연산자 '&'와 '|'를 사용해 여러 조건 조합 가능.
# 각 조건은 반드시 괄호로 묶어야 함.
# '&'은 모든 조건을 만족하는 값, '|'는 하나라도 만족하는 값을 선택함.
scores_bi = np.array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])          # 여러 조건을 조합하기.

# 80점 이상 90점 미만인 점수를 출력하기.
print(f"80점 이상 90점 미만인 점수 출력 ==> {np.array2string(scores_bi[(scores_bi >= 80) & (scores_bi < 90)], separator=', ')}")

# 70점 미만 또는 95점 이상인 점수 출력하기.
print(f"70점 미만 또는 95점 이상인 점수 출력 ==> {np.array2string(scores_bi[(scores_bi < 70) | (scores_bi >= 95)], separator=', ')}")

80점 이상 90점 미만인 점수 출력 ==> [80, 85, 80, 80]
70점 미만 또는 95점 이상인 점수 출력 ==> [65, 95]


In [32]:
# np.where() 함수로 조건에 따른 값 치환하기.
# np.where() 함수는 조건에 따라 서로 다른 값을 할당할 때 사용.
# 첫 번째 인자: 조건, 두 번째 인자: 조건이 True일 때의 할당할 값, 세 번째 인자: 조건이 False 일 때 치환할 값.
scores = np.array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

# 90점 이상인 경우 'A', 아니면 'B'를 할당하는 코드.
grades = np.where(scores >= 90, 'A', 'B')
print(grades)

['B' 'A' 'B' 'B' 'B' 'A' 'A' 'B' 'B' 'B']


In [33]:
# method chain(메서드 체인)
# 여러 개의 메서드를 연속해서 이어서 호출하는 것.
# np.arange(16).reshape(4, 4) ==> 이것도 method chain 기법을 사용한 것. np.arange() 메서드 뒤 .reshape 메서드 사용.
# method chain은 불필요한 변수를 생성하지 않고 코드 라인을 줄려 가독성을 높일 수 있다는 장점이 있음.
# method chain의 단점은 너무 길어지면 코드 작성자 및 읽는 사람이 힘들어짐.

In [36]:
# 2차원 데이터 처리 실무 활용 예제 코드
# 성적표 데이터 (학생 x 과목)
grades = np.array([
    [85, 92, 78, 90],        # 학생 1
    [76, 88, 82, 79],        # 학생 2
    [92, 95, 89, 94],        # 학생 3
    [68, 72, 75, 71]         # 학생 4
])

# 평균 점수가 80점 이상인 학생들 추출.
student_avg = grades.mean(axis=1)
good_students = grades[student_avg >= 80]
print(f"평균이 80점 이상인 학생들의 성적: {np.array2string(good_students, separator=', ')}")

# 모든 과목을 85점 이상 맞은 학생들만 추출
over_85 = grades[grades >= 85]
print(f"모든 과목을 85점 이상 맞은 학생들의 성적: {np.array2string(over_85, separator=', ')}")

평균이 80점 이상인 학생들의 성적: [[85, 92, 78, 90],
 [76, 88, 82, 79],
 [92, 95, 89, 94]]
모든 과목을 85점 이상 맞은 학생들의 성적: [85, 92, 90, 88, 92, 95, 89, 94]
